### ISSUE TITLE
Unable to launch 

### ISSUE THREAD

**Issue by amjith** [imomaliev/ptrepl#20]
I created a temporary virtualenv and installed ptrepl inside. I copied the config snippet from the readme and placed it in `~/.config/ptrepl/config.json` and tried to launch ptrepl. I get the following exception:

```
$ ptrepl git
Traceback (most recent call last):
  File "/Users/amjith/.virtualenvs/tempenv-0f62281434a57/bin/ptrepl", line 11, in <module>
    sys.exit(parse_args())
  File "/Users/amjith/.virtualenvs/tempenv-0f62281434a57/lib/python3.7/site-packages/ptrepl/cli.py", line 92, in parse_args
    main(args.command, prompt=args.prompt)
  File "/Users/amjith/.virtualenvs/tempenv-0f62281434a57/lib/python3.7/site-packages/ptrepl/cli.py", line 19, in main
    history = FileHistory(get_history_file(command, local_shada_path=local_shada_path))
  File "/Users/amjith/.virtualenvs/tempenv-0f62281434a57/lib/python3.7/site-packages/ptrepl/history.py", line 12, in get_history_file
    assert '$' not in path, f"Not all environment variables were expanded {path}"
AssertionError: Not all environment variables were expanded $DIRENV_DIR/.direnv/ptrepl/
```

**Comment by amjith** [comment]
It works. Nice work.

**Comment by imomaliev** [comment]
@amjith I also fixed the issue you were having with starting ptrepl without config
