### ISSUE TITLE
crash when history is empty and I hit enter

### ISSUE THREAD

**Issue by gergelyk** [imomaliev/ptrepl#21]
When I run ptrepl on a given command for the first time and I start from hitting ENTER, ptrepl crashes with following tracebask:

```
Traceback (most recent call last):
  File "/home/foobar/.local/bin/ptrepl", line 10, in <module>
    sys.exit(parse_args())
  File "/home/foobar/.local/lib/python3.7/site-packages/ptrepl/cli.py", line 94, in parse_args
    main(args.command, prompt=args.prompt)
  File "/home/foobar/.local/lib/python3.7/site-packages/ptrepl/cli.py", line 69, in main
    session.default_buffer.history.get_strings()[-1] = subcommand
IndexError: list assignment index out of range
```

**Comment by imomaliev** [comment]
@gergelyk Hi, thanks for feedback, should be fixed in `0.9.6`
